### PR TITLE
Added device types.

### PR DESCRIPTION
**Pull request by nklerk**
I need HDMISWITCH and AUDIO for a project.

These are missing:
  'AUDIO',
  'HDMISWITCH',
  'SOUNDBAR',
  'TUNER'

The folowing can give issues:
THERMOSTAT, CLIMA

### CODE REVIEW

**Comment by pfiaux** [comment]
These types weren't initially added because they have additional requirements. I think we can include them as long as make sure we document the requirements and add validation.

At least that's my assumption, we'll have to check whether that's still true or not. The missing validation should explain issues if you change the SDK to allow some of these type but without adding the required macros to the devices.

**Comment by nklerk** [comment]
I’m exposing the HDMISWITCH and AUDIO in my implementation without any noticeable issues. Hope that helps. :-)

**Comment by pfiaux** [comment]
HDMISWITCH should already be in the nextbranch, as well as TUNER, although I feel like tuner might rely on an `INPUT TUNER 1` as a fallback. I'll double check AUDIO.

**Comment by pfiaux** [comment]
Alright I went through the types and checked for validation and other issues:

- AUDIO – no issues
- HDMISWITCH – needs input validation, also already in next version of SDK
- SOUNDBAR – needs input validation
- TUNER – already in next version of SDK
- THERMOSTAT, CLIMA – known issues (#114)

I've discussed this with @neophob, the main issues is that this targets the master branch and we're currently focused on the next branch and we want to keep the SDK releases synchronized with the Firmware versions. Other minor points:

- Input validation is missing (to generate error if there's no INPUT buttons, see validation/deviceType) for HDMISWITCH
- JSDOC for`setType()` should include the added types (devicebuilder.js)

Considering this we decided to close this (you should be able to use your fork of the SDK if you need them with the current firmware/sdk version). That said I will add AUDIO and SOUNDBAR into the next release and credit you for the changes ;) to make sure we're caught up on the SDK compatible types.

**Pull request closed without merging**
